universe = vanilla
executable = run_job.sh
arguments = $(sample) $(chunk) $(filelist) root://cmseos.fnal.gov//store/user/$ENV(USER)/sidm_condor/AbcdData_2018A_v1 2mu2e_abcd_scan_data,4mu_abcd_scan_data abcd_data unweighted data
transfer_input_files = sidm_code.tar.gz, requirements.txt, $(filelist)
output = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).out
error  = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).err
log    = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).log
request_memory = 4000
request_disk = 4000000
+DesiredOS = "el9"
queue sample, chunk, filelist from job_args_abcd_data_2018A.txt
