universe = vanilla

executable = run_job.sh

arguments = $(sample) $(chunk) $(filelist) root://cmseos.fnal.gov//store/user/$ENV(USER)/sidm_condor/TruthkinChunks_v3 genOnly,genOnly_trigger,baseNoLj_noTrigger,baseNoLj,base gen_truth,genA_lifetime,genBS_genA_kinematics,genA_base,genA_ratio,lj_base,lj_lj_base,muon_base,anatomy_extra

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = sidm_code.tar.gz, requirements.txt, $(filelist)

output = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).out
error  = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).err
log    = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).log

request_cpus = 1
request_memory = 4GB
request_disk = 4GB

x509userproxy = $ENV(X509_USER_PROXY)

queue sample, chunk, filelist from job_args_truthkin_v3.txt
