universe = vanilla

executable = run_job.sh

arguments = $(sample) $(chunk) $(filelist) root://cmseos.fnal.gov//store/user/$ENV(USER)/sidm_condor/TruthkinChunks_v2 genOnly,genOnly_born,genFilterEmulation,genFilterEmulation_isHardProcess,baseNoLj_noTrigger,baseNoLjNoLjsource_noTrigger genA_lifetime,gen_truth,genBS_genA_kinematics,genA_base,lepton_genA_base

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = sidm_code.tar.gz, requirements.txt, $(filelist)

output = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).out
error  = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).err
log    = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).log

request_cpus = 1
request_memory = 4GB
request_disk = 4GB

x509userproxy = $ENV(X509_USER_PROXY)

queue sample, chunk, filelist from job_args_truthkin.txt
