universe = vanilla

executable = run_job.sh

arguments = $(sample) $(chunk) $(filelist) root://cmseos.fnal.gov//store/user/$ENV(USER)/sidm_condor/AbcdScan_v1 4mu_abcd_scan,2mu2e_abcd_scan abcd_scan weighted

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = sidm_code.tar.gz, requirements.txt, $(filelist)

output = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).out
error  = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).err
log    = logs/$(sample)_$(chunk)_$(Cluster)_$(Process).log

request_cpus = 1
request_memory = 4GB
request_disk = 4GB

x509userproxy = $ENV(X509_USER_PROXY)

queue sample, chunk, filelist from job_args_abcd_scan.txt
